spring:
  datasource:
    url: jdbc:mysql://${DB_ADDR}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PW}
    driver-class-name: ${DB_DRIVER}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  profiles:
    active: local

logging:
  level:
    org.springframework.security: DEBUG
