spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: 
    username: 
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org.springframework: INFO
    com.example.demo: DEBUG
cloud:
  aws:
    s3:
      bucket: 
    credentials:
      access-key: 
      secret-key: 
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

project:
  upload:
    path: C:\Users\Playdata\IdeaProjects\ex\demo\src\main\resources\static\images



